# Generated by Django 2.1.2 on 2018-10-25 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Sexo_mascota',
            field=models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_mascota',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento_mascota',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
    ]
