# Generated by Django 2.1.2 on 2018-10-25 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181025_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento_mascota',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
